### ISSUE TITLE
Soft delete is not working through the Repository builder

### ISSUE THREAD

**Issue by Casperhr** [nodes-php/database#1]
The soft delete trait is ignored on all queries through the repository extending this repo.
If you use the query builder through $this->model it works perfect. 

$this->model->first() will give me a none soft deleted item
$this->first() gives me a soft deleted item

We should also consider solving the construct warning

**Comment by rugaard** [comment]
Fixed in commit: https://github.com/nodes-php/database/commit/5422b1acdb93923257f48c20278c29bbb7c4787a
