### ISSUE TITLE
Doing 2 finds in same request in same repo is not resetting query between them

### ISSUE THREAD

**Issue by Casperhr** [nodes-php/database#4]
$one = $this->getBy('code', 'test1');
$two = $this->getBy('code', 'test2');

dd($one, $two); 

object
null

$two = $this->getBy('code', 'test2');
$one = $this->getBy('code', 'test1');

dd($one, $two); 

null
object

$this->getModel() and it works

**Comment by rugaard** [comment]
Fixed in release 0.1.5.
